### ISSUE TITLE
send stanza via mod_rest with authentication

### ISSUE THREAD

**Issue by khanhvu161188** [processone/ejabberd-contrib#142]
Can u give me 1 sample for calling with wget?
i want to send a stanza, also i need authentication so that xmpp server just allow with username/password like you send command 

```
If you configure access_commands option, you must provide the credentials like this:
 wget http://localhost:5280/rest/ --server-response --post-data '--auth user1 localhost thepass registered_users localhost'
```

**Comment by badlop** [comment]
That isn't possible with the mod_rest feature to send stanzas. I've added a command to ejabberd's mod_admin_extra called send_stanza, because commands do support access restrictions.

So, you need ejabberd from recent git, install mod_rest, and configure like this:
```
acl:
  admin:
    user:
      - "user1": "localhost"

listen:
  -
    port: 5280
    module: ejabberd_http
    request_handlers:
      "/rest": mod_rest

modules:
  mod_rest:
    allowed_ips:
      - "127.0.0.1"
    access_commands:
      configure:
        - send_stanza
  mod_admin_extra: {}
```

Then this call works as expected:
```
$ wget http://localhost:5280/rest/ --server-response --post-data
"--auth user1 localhost mypass11
 send_stanza localhost user22@localhost
 \"<message to='user22@localhost' from='localhost/rest'><body>World</body></message>\""
```
