### ISSUE TITLE
Using the module ejabberd_auth_http

### ISSUE THREAD

**Issue by may215** [processone/ejabberd-contrib#143]
I have currently tried to set up ejabberd_auth_http for http authorization via my web application and I can't make it work.

Some setting backgrounds:
- Using ejabberd 15.11 in centos
- Not register any user internally before
- Use localhost
- For extra module, only ejabberd_auth_http is installed
- All ejabberd_auth_http option setting is same as the setting of the example in README file of ejabberd_auth_http
- Register module is enable

Auth config:
```
auth_method: http
auth_opts:
  host: "http://e6d111d5.ngrok.io"
  connection_pool_size: 10
  connection_opts: []
  basic_auth: ""
  path_prefix: "/"
```

The request I am trying to make:
```
curl -X POST http://192.168.99.103:5280/register --data-urlencode 'type=plain&user=test&server=localhost&pass=password'
```

From my web application server log, I not getting any request from ejabberd. The crashes/error logs are empty and I get the following logs in ejabberd.log:
```
2016-01-01 10:11:54.906 [info] <0.3436.0>@ejabberd_listener:accept:299 (#Port<0.84005>)
 Accepted connection 192.168.99.1:59924 -> 172.17.0.4:5280
2016-01-01 10:11:54.906 [info] <0.3441.0>@ejabberd_http:init:157 started:
 {p1_tls,{tlssock,#Port<0.84005>,#Port<0.84008>}}

```
What do I missing here?
