### ISSUE TITLE
mod_archive_odbc

### ISSUE THREAD

**Issue by ikawka** [processone/ejabberd-contrib#15]
Hello,

I've managed to have this compiled and loaded the module.

here's from the configuration file
```
mod_archive_odbc:
    database_type: mysql
    default_auto_save: true
    enforce_default_auto_save: true
    default_expire: "infinity"
    enforce_min_expire: 0
    enforce_max_expire: "infinity"
    replication_expire: 31536000
```
but after restarting the ejabberd i got this error
```
2014-03-07 16:01:08.866 [error] <0.9739.0> CRASH REPORT Process <0.9739.0> with 0 neighbours exited with reason: no case clause matching undefined in gen_iq_handler:add_iq_handler/6 line 65 in gen_server:init_it/6 line 328
```

hoping you guys could shed some light on the one. thank you very much
