### ISSUE TITLE
mod_rest "module_must_be_started_in_vhost" error

### ISSUE THREAD

**Issue by rastkojokic** [processone/ejabberd-contrib#150]
When I try to post any kind of request to rest api I get the following error:

request:
```
wget localhost:5280/rest --server-response --post-data '<some data>'
```

error:
```
CRASH REPORT Process <0.494.0> with 0 neighbours crashed with reason: {module_must_be_started_in_vhost,mod_rest,<<"localhost">>} in mod_rest:try_get_option/3 line 107
```

My ejabberd.yml and its' relevant parts are like this:

```
hosts:
  - "virtualhost-dev"

...
modules:
  mod_rest:
     allowed_ips:
       - all
     access_commands:
       rest:
         registered_users:
           - all
         connected_users:
           - all
     allowed_destinations:
        - all
     allowed_stanza_types:
        - all
```
