### ISSUE TITLE
mod_cron not working on 16.02

### ISSUE THREAD

**Issue by joanlopez** [processone/ejabberd-contrib#165]
Hi,

I have the example configuration as the documentation explains:
```
mod_cron:  
  tasks:
    - time: 10
      units: seconds
      module: mnesia
      function: info
      arguments: {}
      timer_type: interval
```

And I'm getting the next error:

```
[error] <0.37.0>@gen_mod:stop_module_keep_config:136 {badarg,[
{ets,select,[cron_tasks,[{{task,'_','_',<<"xmpp.qbitapp.com">>,'_'},[],['$_']}]],[]},
{mod_cron,get_tasks,1,[{file,"src/mod_cron.erl"},{line,194}]},
{mod_cron,stop,1,[{file,"src/mod_cron.erl"},{line,49}]},
{gen_mod,stop_module_keep_config,2,[{file,"src/gen_mod.erl"},{line,135}]},
{lists,foreach,2,[{file,"lists.erl"},{line,1336}]},
{ejabberd_app,prep_stop,1,[{file,"src/ejabberd_app.erl"},{line,86}]},
{application_master,prep_stop,2,[{file,"application_master.erl"},{line,376}]},
{application_master,loop_it,4,[{file,"application_master.erl"},{line,352}]}]}`
```
How I should configure the tasks?

I've also tried with my own module and neither.

Thanks!
