### ISSUE TITLE
account_unprivileged - ejabberd_16.06.

### ISSUE THREAD

**Issue by pebbleping** [processone/ejabberd-contrib#183]
Hi, 

I am new with ejabberd. 
I got this error once I try to use xmlrpc client to run the command "status".

Error : A problem '{error,account_unprivileged}' occurred executing the command status with arguments

Config in ejabberd.yml.

```
all:
  admin:
    user:
      - "admin@localhost"

 -
     port: 4560
     module: ejabberd_xmlrpc
     maxsessions: 10
     timeout: 5000
     access_commands:
       admin:
         commands: all
         options: []
```

Client code 

```
XmlRpcClientConfigImpl config = new XmlRpcClientConfigImpl();
            config.setServerURL(new URL("http://localhost:4560"));
            config.setBasicUserName("admin");
            config.setBasicPassword("test1234");

            XmlRpcClient client = new XmlRpcClient();
            client.setConfig(config);

            /* Command string */

            String command = "status";

            /* Parameters as struct */
            Map struct = new HashMap();

            Object[] params = new Object[]{struct};
            Integer result = (Integer) client.execute(command, params);
```

Any idea?
