### ISSUE TITLE
Ejabberd 17.04 unknown option 'auth_opts' will be likely ignored

### ISSUE THREAD

**Issue by Hassnain-Raza-Alvi** [processone/ejabberd-contrib#210]
Hi,|
I have installed Ejabberd 17.04 and installed **ejabberd_auth_http** module and followed the instructions specified [here](https://github.com/processone/ejabberd-contrib/tree/master/ejabberd_auth_http)

But it does not pick up the auth_opts and said its unknown. Here is my configuration
```
auth_method: http
auth_opts:
  host: "http://localhost:9095"
  connection_pool_size: 10
  connection_opts: []
  basic_auth: ""
  path_prefix: "/"
```
Here is the error message:
**unknown option 'auth_opts' will be likely ignored**

Can someone tell me the issue here?
