### ISSUE TITLE
ejabberd_auth_http unknown option 'auth_opts' will be likely ignored

### ISSUE THREAD

**Issue by Hassnain-Raza-Alvi** [processone/ejabberd-contrib#211]
I am running latest **ejabberd 17.04** and using **ejabberd_auth_http** module
Here is my configuration

```
auth_method: http
auth_opts:
  host: "http://localhost:9095"
  connection_pool_size: 10
  connection_opts: []
  basic_auth: ""
  path_prefix: "/"
```

Here is the error that i am getting

> 2017-04-19 11:45:12.970 [error] <0.635.0>@ejabberd_config:validate_opts:1012 unknown option 'auth_opts' will be likely ignored

Can you tell me is this module working on ejabberd 17.04? if its not working is there any alternative that i can use for now?
