### ISSUE TITLE
mod_logxml configuration 

### ISSUE THREAD

**Issue by interda** [processone/ejabberd-contrib#220]
I edit modules section in ejabberd.yml 
```yaml
  mod_logxml:
     stanza:
       - message
     direction:
       - internal
       - vhosts
     orientation:
       - send
       - recv
     logdir: "/var/log/ejabberd/logs/"
```
But module start with default config. Logdir -/tmp/logs/ and stanza - iq, other and direction -external. Ejabberd 17.07
