### ISSUE TITLE
Failed with error: "inexistent-account"

### ISSUE THREAD

**Issue by Adiii717** [processone/ejabberd-contrib#246]
I tried to configure `auth_method: http` in ejabberd.yml.

The first thing my node server API never get called from ejabberd.

Here is my configuration.

```
auth_method: http
auth_opts:
  host: "http://192.168.1.23:3000"
  connection_pool_size: 10
  connection_opts: []
  basic_auth: ""
  path_prefix: "/"
```
But i tried to login using admin panel got below error.

`[warning] <0.485.0>@ejabberd_web_admin:process:246 Access of <<"admin@localhost">> from <<"::ffff:172.17.0.1">> failed with error: <<"inexistent-account">>
`
Thanks.
