### ISSUE TITLE
there is no roster with using ejabberd_auth_hpp on ejabberd 18.09

### ISSUE THREAD

**Issue by damirci** [processone/ejabberd-contrib#266]
Hi,
I enabled ejabberd_auth_http on ejabberd 18.09 and I configured using SQL for `mod_roster` and is set `default_db : sql`  but does not save rosters. can I have `ejabberd_auth_http` and saving rosters together?!

I have to say that all tables are empty and there is no record for archives, online user and ... .

**Comment by badlop** [comment]
> can I have ejabberd_auth_http and saving rosters together?!

Yes, you can use an authentication method (mnesia, sql, external script, whatever), and configure the modules to use whatever storage method you want.

So, you have configured something like this, but nothing is stored in your database?
```yaml
auth_method: http
default_db: sql
host_config:
  "localhost":
    sql_type: mysql
...
```
What happens if you:
* configure internal auth, and default_db: sql... is it correctly stored in sql?
* configure http auth, and default_db: mnesia... is it correctly stored in mnesia?

**Comment by damirci** [comment]
Thanks, that solved with adding
```yaml
host_config:
  "localhost":
    sql_type: mysql
```
to config file.
