### ISSUE TITLE
ejabberd_auth_http does not call external REST point

### ISSUE THREAD

**Issue by vkelman** [processone/ejabberd-contrib#270]
ejabberd version: 19.02
OS: Windows 10
Installed from: official binary installer
ejabberd_auth_http installed

ejabberd.yml:

```
language: "en"
hosts:
  - "planetrisk.com"

auth_method: http

auth_opts:
  host: "http://localhost:80"
  connection_pool_size: 10
  connection_opts: []
  basic_auth: ""
  path_prefix: "services/imd35000/api/v1/ejabberd/"

auth_use_cache: false

  ## mod_register:
```

So, mod_register is disabled (commented out), I implemented web service controller stub in C# which listens on  http://localhost/services/imd35000/api/v1/ejabberd route.
Two get methods are implemented, check_password and user_exists.

I use POSTMAN to perform calls like 

`http://localhost:80/services/imd35000/api/v1/ejabberd/check_password?user=testfouoles&server=planetrisk.com&pass=fsdfsddds
`
and
`http://localhost/services/imd35000/api/v1/ejabberd/user_exists?user=testfouoles&server=planetrisk.com&pass=fsdfsddds`

Both calls work and when running web service in a debugger, it stops on break points.

ejabberd ejabberd_auth_http  does not call this API.

In ejabberd.log I see 

> 2019-04-18 17:23:51.402 [warning] <0.534.0>@ejabberd_c2s:handle_auth_failure:452 (http_bind|<0.533.0>) Failed c2s PLAIN authentication for testfouoles@planetrisk.com from 127.0.0.1: Invalid username or password

The same thing happens if I try to login using ejabberd web admin console.
