### ISSUE TITLE
how to enable additional stats from statsdx

### ISSUE THREAD

**Issue by aditya-enthu** [processone/ejabberd-contrib#306]
Hello All, 

Learning ejabbered and trying to understand how to enable additional stats.

Let's say I would like to uncomment below line. How do I apply or what actions do I need to take to show these stats in web admin portal.

I tried multiple commands but it doesn't show up.
- module_uninstall mod_statsdx
- module_install mod_statsdx
- module_update spec 

https://github.com/processone/ejabberd-contrib/blob/c2efdc19506b255f4b74cdc4c805eab6128c2173/mod_statsdx/src/mod_statsdx.erl#L1358-L1365

Can someone please guide with exact steps.

**Comment by licaon-kter** [comment]
And you added the module to .yml and reloaded or restarted, yes?

**Comment by aditya-enthu** [comment]
@licaon-kter thank you for quick response.

Nope, when I add module to /opt/ejabberd/conf/ejabberd.yml it crashes/error out.

```
mod_statsdx: {}
   hooks : true
```

But it runs fine when I install 
```ejabberdctl module_install mod_statsdx ```

running ejabberd version - 21.07 on ubuntu 20.04

**Comment by licaon-kter** [comment]
You need to do both.

When it errors out, what's the .log message?

**Comment by aditya-enthu** [comment]
I found that the module is enabled in this file (not my change seems by defaullt), do I still need to enable at /opt/ejabberd/conf/ejabberd.yml

```
cat /opt/ejabberd/.ejabberd-modules/mod_statsdx/conf/mod_statsdx.yml
modules:
  mod_statsdx:
    hooks: true
  mod_stats2file:
    interval: 60
    type: txt
    split: true
    basefilename: "/var/www/stats"
    hosts:
      - "localhost"
```
