### ISSUE TITLE
mod_rest not compatibility with YAML

### ISSUE THREAD

**Issue by beherit** [processone/ejabberd-contrib#45]
mod_rest is not compatibility with YAML config file - could You fix it?

**Comment by Beherit** [comment]
mod_rest still don't have compatibility with YAML. Maybe @badlop could fix that?

**Comment by dollarhand** [comment]
Hi Beherit,
I have used the below config, in listen and module and  they are working for me.  May you can try out this 

listen:
 port: 5280
    module: ejabberd_http
    request_handlers:
      "/rest": mod_rest
    web_admin: true
    http_poll: true
    http_bind: true
    ## register: true
    captcha: true

	
modules:
  mod_rest:
    allowed_ips:
      - all
    access_commands:
      rest:
        registered_users:
          - all
        connected_users:
          - all
    allowed_destinations:
      - all
    allowed_stanza_types:
        - all

**Comment by Beherit** [comment]
I don't want allow all and it's the point of problem. It isn't a way to configure "access_commands" to access only some types of commands and do not allow any types of stanza.

**Comment by dagingaa** [comment]
Was just frustrated by this as well. Copy-pasting the suggested configuration didn't work. But having empty config worked just fine (`mod_rest: []`), so I'll have to secure it by external means, which is fine for now.

**Comment by badlop** [comment]
I've applied a simplification in ejabberd source code 7ab6c4b, and now this config:
```
acl:
  admin:
    user:
      - "user1": "localhost"

access:
  configure:
    admin: allow

listen:
  - 
    port: 5280
    module: ejabberd_http
    request_handlers:
      "/rest": mod_rest

modules:
  mod_rest:
    allowed_ips:
      - "127.0.0.1"
    access_commands:
      configure:
        - registered_users
        - connected_users
    allowed_destinations: all
    allowed_stanza_types: all
```

Allows this to work:
```
wget http://localhost:5280/rest/ --server-response
 --post-data '--auth user1 localhost mypass registered_users localhost'
```
